services:
  bot:
    image: ${DOCKER_USERNAME}/${PROJECT_NAME}:latest
    env_file:
      - .env
    depends_on:
      - pgbouncer
    networks:
      - bot_network

  postgres:
    image: postgres:17.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    networks:
      - bot_network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      start_period: 5s

  pgbouncer:
    image: bitnami/pgbouncer:1.24.0
    ports:
      - "${PGBOUNCER_PORT}:6432"
    environment:
      - POSTGRESQL_HOST=postgres
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - bot_network

  notifier:
    restart: unless-stopped
    image: lorcas/docker-telegram-notifier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    labels:
      telegram-notifier.monitor: false


networks:
  bot_network:
    driver: bridge


volumes:
  postgres-data:
