services:
  bot:
    image: ${ENV_DOCKER_USERNAME}/${ENV_PROJECT_NAME}-bot:latest
    env_file:
      - .env
    depends_on:
      - pgbouncer
    networks:
      - app-network
    volumes:
      - app-logs:/app/logs

  api:
    image: ${ENV_DOCKER_USERNAME}/${ENV_PROJECT_NAME}-api:latest
    env_file:
      - .env
    depends_on:
      - pgbouncer
    networks:
      - app-network
    volumes:
      - app-logs:/app/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${API_PORT}/api/v1/health/" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 3s

  postgres:
    image: postgres:17.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 3s

  pgbouncer:
    image: bitnami/pgbouncer:1.24.0
    ports:
      - "${PGBOUNCER_PORT}:6432"
    environment:
      - POSTGRESQL_HOST=postgres
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app-network

  notifier:
    restart: unless-stopped
    image: lorcas/docker-telegram-notifier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    labels:
      telegram-notifier.monitor: false


networks:
  app-network:
    driver: bridge


volumes:
  postgres-data:
  app-logs:
