name: scheduler

services:
  bot:
    build:
      context: .
      dockerfile: ./src/bot/Dockerfile
      target: ${ENV_MODE}
    volumes:
      - ./src/bot:/app/src/bot
      - ./src/migrations:/app/src/migrations
    env_file:
      - .env
    depends_on:
      - pgbouncer
    networks:
      - bot_network

  postgres:
    image: postgres:17.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    networks:
      - bot_network

  pgbouncer:
    image: bitnami/pgbouncer:1.24.0
    ports:
      - "${PGBOUNCER_PORT}:6432"
    environment:
      - POSTGRESQL_HOST=postgres
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - bot_network


networks:
  bot_network:
    driver: bridge

volumes:
  postgres-data: