name: ${ENV_PROJECT_NAME}

x-service-defaults: &service_defaults
  env_file:
    - .env
  networks:
    - app-network

x-app-logs-defaults: &app_logs_defaults
  volumes:
    - app-logs:/app/logs


x-healthcheck-defaults: &healthcheck_defaults
  interval: "${ENV_DOCKER_HEALTHCHECK_INTERVAL}"
  timeout: "${ENV_DOCKER_HEALTHCHECK_TIMEOUT}"
  retries: ${ENV_DOCKER_HEALTHCHECK_RETRIES}
  start_period: "${ENV_DOCKER_HEALTHCHECK_START_PERIOD}"

x-celery-opts: &celery_opts
  image: ${ENV_DOCKER_USERNAME}/${ENV_PROJECT_NAME}-bot:latest
  depends_on:
    redis:
      condition: service_healthy
  healthcheck:
    test: [ "CMD", "celery", "-A", "bot.celery.celery_app", "inspect", "ping" ]
    <<: *healthcheck_defaults


services:
  api:
    image: ${ENV_DOCKER_USERNAME}/${ENV_PROJECT_NAME}-api:latest
    container_name: ${ENV_PROJECT_NAME}-api
    profiles:
      - api
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      pgbouncer:
        condition: service_started
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://${API_HOST}:${API_PORT}${API_HEALTHCHECK_PATH}" ]
      <<: *healthcheck_defaults
    <<: [ *service_defaults, *app_logs_defaults]

  bot:
    image: ${ENV_DOCKER_USERNAME}/${ENV_PROJECT_NAME}-bot:latest
    container_name: ${ENV_PROJECT_NAME}-bot
    restart: unless-stopped
    depends_on:
      pgbouncer:
        condition: service_started
      redis:
        condition: service_healthy
    <<: [ *service_defaults, *app_logs_defaults]

  celery-worker:
    container_name: ${ENV_PROJECT_NAME}-celery-worker
    command: celery -A bot.celery.celery_app worker -P eventlet -l ${LOG_LEVEL}
    <<: [ *service_defaults, *app_logs_defaults, *celery_opts ]

  celery-beat:
    container_name: ${ENV_PROJECT_NAME}-celery-beat
    command: celery -A bot.celery.celery_app beat -l ${LOG_LEVEL}
    profiles:
      - celery-beat
    <<: [ *service_defaults, *app_logs_defaults, *celery_opts ]

  postgres:
    image: postgres:17.5-alpine
    container_name: ${ENV_PROJECT_NAME}-postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${POSTGRES_DB}" ]
      <<: *healthcheck_defaults
    <<: *service_defaults

  pgbouncer:
    image: bitnami/pgbouncer:1.24.1
    container_name: ${ENV_PROJECT_NAME}-pgbouncer
    ports:
      - "${PGBOUNCER_PORT}:${PGBOUNCER_PORT}"
    environment:
      - POSTGRESQL_HOST=postgres
    depends_on:
      postgres:
        condition: service_started
    <<: *service_defaults

  redis:
    image: redis:8.0.2-alpine
    container_name: ${ENV_PROJECT_NAME}-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: [ "redis-server", "--port", "${REDIS_PORT}" ]
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "${REDIS_PORT}", "ping" ]
      <<: *healthcheck_defaults
    <<: *service_defaults

  tester:
    build:
      context: .
      dockerfile: ./src/tests/Dockerfile
    profiles:
      - testing
    <<: *service_defaults


networks:
  app-network:
    driver: bridge


volumes:
  postgres-data:
  redis-data:
  app-logs:
