name: scheduler

services:
  bot:
    build:
      context: .
      dockerfile: ./src/bot/Dockerfile
      target: ${ENVIRONMENT}
    volumes:
      - ./src/bot:/app/src/bot
    env_file:
      - .env