services:
  bot:
    build:
      context: .
      dockerfile: ./src/bot/Dockerfile
      target: ${ENV_MODE}
    volumes:
      - ./src:/app/src
    depends_on:
      - pgbouncer
      - redis
      - api

  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
      target: ${ENV_MODE}
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./src:/app/src
    healthcheck:
      test: placeholder
      disable: true
    depends_on:
      - pgbouncer
      - redis

  postgres:
    healthcheck:
      test: placeholder
      disable: true

  pgbouncer:
    depends_on:
      - postgres

  redis:
    healthcheck:
      test: placeholder
      disable: true

  tester:
    volumes:
      - ./src:/app/src

  notifier:
    profiles:
      - none
