name: scheduler

services:
  bot:
    build:
      context: .
      dockerfile: ./src/bot/Dockerfile
      target: ${ENVIRONMENT}
    volumes:
      - ./src/bot:/app/src/bot
    env_file:
      - .env

  postgres:
    image: postgres:17.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env


volumes:
  postgres-data: