services:
  bot:
    build:
      context: .
      dockerfile: ./src/bot/Dockerfile
      target: ${ENV_MODE}
    volumes:
      - ./src:/app/src

  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
      target: ${ENV_MODE}
    volumes:
      - ./src:/app/src

  celery-worker:
    build:
      context: .
      dockerfile: ./src/bot/Dockerfile
      target: ${ENV_MODE}
    volumes:
      - ./src:/app/src

  celery-beat:
    build:
      context: .
      dockerfile: ./src/bot/Dockerfile
      target: ${ENV_MODE}
    volumes:
      - ./src:/app/src

  tester:
    volumes:
      - ./src:/app/src
