name: scheduler

services:
  bot:
    build:
      context: .
      dockerfile: ./src/bot/Dockerfile
      target: ${ENV_MODE}
    volumes:
      - ./src/bot:/app/src/bot
      - ./src/logger:/app/src/logger
    env_file:
      - .env
    depends_on:
      - pgbouncer

  postgres:
    image: postgres:17.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env

  pgbouncer:
    image: bitnami/pgbouncer:latest
    ports:
      - "${PGBOUNCER_PORT}:6432"
    environment:
      - POSTGRESQL_HOST=postgres
    env_file:
      - .env
    depends_on:
      - postgres


volumes:
  postgres-data: