name: ${ENV_PROJECT_NAME}

x-healthcheck-defaults: &healthcheck_defaults
  interval: "${ENV_DOCKER_HEALTHCHECK_INTERVAL}"
  timeout: "${ENV_DOCKER_HEALTHCHECK_TIMEOUT}"
  retries: ${ENV_DOCKER_HEALTHCHECK_RETRIES}
  start_period: "${ENV_DOCKER_HEALTHCHECK_START_PERIOD}"

x-celery-opts: &celery_opts
  image: ${ENV_DOCKER_USERNAME}/${ENV_PROJECT_NAME}-bot:latest
  env_file:
    - .env
  volumes:
    - app-logs:/app/logs
  networks:
    - app-network
  depends_on:
    redis:
      condition: service_started

services:
  bot:
    image: ${ENV_DOCKER_USERNAME}/${ENV_PROJECT_NAME}-bot:latest
    container_name: ${ENV_PROJECT_NAME}-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - app-logs:/app/logs
    networks:
      - app-network
    depends_on:
      pgbouncer:
        condition: service_started
      redis:
        condition: service_healthy

  api:
    image: ${ENV_DOCKER_USERNAME}/${ENV_PROJECT_NAME}-api:latest
    container_name: ${ENV_PROJECT_NAME}-api
    profiles:
      - api
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    volumes:
      - app-logs:/app/logs
    networks:
      - app-network
    depends_on:
      pgbouncer:
        condition: service_started
      redis:
        condition: service_healthy
    healthcheck:
      <<: *healthcheck_defaults
      test: ["CMD", "wget", "-q", "--spider", "http://${API_HOST}:${API_PORT}/api/v1/health"]

  celery-worker:
    container_name: ${ENV_PROJECT_NAME}-celery-worker
    command: celery -A bot.celery.celery_app worker -P eventlet -l ${LOG_LEVEL}
    <<: *celery_opts

  celery-beat:
    container_name: ${ENV_PROJECT_NAME}-celery-beat
    command: celery -A bot.celery.celery_app beat -l ${LOG_LEVEL}
    profiles:
      - celery-beat
    <<: *celery_opts

  postgres:
    image: postgres:17.4-alpine
    container_name: ${ENV_PROJECT_NAME}-postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      <<: *healthcheck_defaults
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${POSTGRES_DB}" ]

  pgbouncer:
    image: bitnami/pgbouncer:1.24.0
    container_name: ${ENV_PROJECT_NAME}-pgbouncer
    ports:
      - "${PGBOUNCER_PORT}:${PGBOUNCER_PORT}"
    environment:
      - POSTGRESQL_HOST=postgres
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:8.0.0-alpine
    container_name: ${ENV_PROJECT_NAME}-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: [ "redis-server", "--port", "${REDIS_PORT}" ]
    volumes:
      - redis-data:/var/lib/redis/data
    networks:
      - app-network
    healthcheck:
      <<: *healthcheck_defaults
      test: [ "CMD", "redis-cli", "-p", "${REDIS_PORT}", "ping" ]

  tester:
    build:
      context: .
      dockerfile: ./src/tests/Dockerfile
    profiles:
      - testing
    env_file:
      - .env
    networks:
      - app-network


networks:
  app-network:
    driver: bridge


volumes:
  postgres-data:
  redis-data:
  app-logs:
