x-project-opts: &project_opts
  image: "" # Для dev разработки не нужен image

x-shared-volumes: &shared_volumes
  volumes:
    - ./src:/app/src

x-build-defaults: &build_defaults
  context: .
  target: ${ENV_MODE}

x-bot-defaults: &bot_defaults
  build:
    dockerfile: ./src/bot/Dockerfile
    <<: *build_defaults
  <<: [ *project_opts, *shared_volumes ]


services:
  api:
    build:
      dockerfile: src/api/Dockerfile
      <<: *build_defaults
    <<: [ *project_opts, *shared_volumes ]

  bot:
    <<: *bot_defaults

  celery-worker:
    command: hupper -q -m celery -A bot.celery.celery_app worker -P eventlet -l ${LOG_LEVEL}
    <<: *bot_defaults

  celery-beat:
    command: hupper -q -m celery -A bot.celery.celery_app beat -l ${LOG_LEVEL}
    <<: *bot_defaults

  tester:
    <<: *shared_volumes
