services:
  bot:
    build:
      context: .
      dockerfile: ./src/bot/Dockerfile
      target: ${ENV_MODE}
    volumes:
      - ./src:/app/src

  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
      target: ${ENV_MODE}
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ./src:/app/src

  notifier:
    profiles:
      - none
