"""added to_chat_id to delayed message model

Revision ID: b7b55ad8aa33
Revises: da6581a6c509
Create Date: 2025-05-27 10:46:03.336944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b55ad8aa33'
down_revision: Union[str, None] = 'da6581a6c509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delayed_messages', sa.Column('to_chat_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delayed_messages', 'to_chat_id')
    # ### end Alembic commands ###
