"""added delayed message

Revision ID: da6581a6c509
Revises: 729114d51771
Create Date: 2025-05-26 16:18:05.432820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6581a6c509'
down_revision: Union[str, None] = '729114d51771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delayed_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('message_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delayed_messages')
    # ### end Alembic commands ###
