"""updated timezone_offset field for user

Revision ID: 552cc0556899
Revises: ac10b25126cd
Create Date: 2025-06-09 17:22:44.656089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552cc0556899'
down_revision: Union[str, None] = 'ac10b25126cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone_offset', sa.Integer(), nullable=True))
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'timezone_offset')
    # ### end Alembic commands ###
