"""

Revision ID: 729114d51771
Revises: 2e87c373a903
Create Date: 2025-05-04 00:04:36.431896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729114d51771'
down_revision: Union[str, None] = '2e87c373a903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Удаляем дубли каналов для пользователей
    op.execute("""
        DELETE FROM channels
        WHERE id NOT IN (
            SELECT MIN(id)
            FROM channels
            GROUP BY user_id, chat_id
        )
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_chat', 'channels', ['user_id', 'chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_chat', 'channels', type_='unique')
    # ### end Alembic commands ###
