# $schema: https://json.schemastore.org/github-action.json

name: Telegram Notify
description: 'Send notification to Telegram'

inputs:
  job_name:
    description: 'Name of the failed job'
    required: true
  to:
    description: 'Telegram Chat ID'
    required: true
  token:
    description: 'Telegram Bot Token'
    required: true

runs:
  using: composite
  steps:
    - name: Send Telegram Notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ inputs.to }}
        token: ${{ inputs.token }}
        message: |
          *Job*: ${{ inputs.job_name }}
          *Repository*: {{ repo }}
          *Namespace*: {{ repo.namespace }}
          *Commit SHA*: {{ commit.sha }}
          *Ref*: {{ commit.ref }}
          *Workflow*: {{ github.workflow }}
          *Event*: {{ github.event.name }}
          *Actor*: {{ repo.namespace }}quest.title }}