# $schema: https://json.schemastore.org/github-action.json

name: Telegram Notify
description: 'Send notification to Telegram'

inputs:
  job_name:
    description: 'Name of the failed job'
    required: true
  to:
    description: 'Telegram Chat ID'
    required: true
  token:
    description: 'Telegram Bot Token'
    required: true

runs:
  using: composite
  steps:
    - name: Send Telegram Notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ inputs.to }}
        token: ${{ inputs.token }}
        message: |
          ❌ Failed commit ${{ github.event.head_commit.message }} from ${{ github.actor }}:
          CI Job "${{ inputs.job_name }}" in ${{ github.repository }}
          
          Job link:
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
