# $schema: https://json.schemastore.org/github-action.json

name: Telegram Notify
description: 'Send notification to Telegram'

inputs:
  job_name:
    description: 'Name of the failed job'
    required: true
  to:
    description: 'Telegram Chat ID'
    required: true
  token:
    description: 'Telegram Bot Token'
    required: true

runs:
  using: composite
  steps:
    - name: Send Telegram Notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ inputs.to }}
        token: ${{ inputs.token }}
        message: |
          ❌ *Job Failure Alert* ❌

          *Job*: ${{ inputs.job_name }}
          *Repository*: ${{ github.repository }}
          *Event*: ${{ github.event_name }}
          *Author*: ${{ github.actor }}
          *Branch/PR*: ${{ github.event.pull_request.title || github.ref_name }}

          🔗 [View Workflow Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
