# $schema: https://json.schemastore.org/github-action.json

name: Telegram Notify
description: 'Send notification to Telegram'

inputs:
  job_name:
    description: 'Name of the failed job'
    required: true
  to:
    description: 'Telegram Chat ID'
    required: true
  token:
    description: 'Telegram Bot Token'
    required: true

runs:
  using: composite
  steps:
    - name: Send Telegram Notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ inputs.to }}
        token: ${{ inputs.token }}
        format: markdown
        message: |
          *Repository*: ${{ github.server_url }}/${{ github.repository }}
          *Actor*: {{ repo.namespace }}
          *Job*: ${{ inputs.job_name }}
          
          [Workflow Link](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}):

#        message: |
#
#          *Job*: ${{ inputs.job_name }}
#          *Repository*: ${{ github.repository }}
#          *Event*: ${{ github.event_name }}
#          *Author*: ${{ github.actor }}
#          *PR*: ${{ github.event.pull_request.title }}
#
#          🔗 [View Workflow Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
