# $schema: https://json.schemastore.org/github-workflow.json

name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-cd-${{ github.ref }}
  cancel-in-progress: true

env:
  COMPOSE_BAKE: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  test:
    needs: [ lint ]
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build:
    needs: [ test ]
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    needs: [ build ]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
