# $schema: https://json.schemastore.org/github-action.json

name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  build:
    needs:
      - lint
    uses: ./.github/workflows/build.yml
    secrets: inherit
