# $schema: https://json.schemastore.org/github-workflow.json

name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh

      - name: Install dependencies
        run: uv sync --dev

      - name: Run linters
        run: make lint

      - name: Notify Telegram on Failure
        if: failure()
        uses: ./.github/actions/telegram-notify
        with:
          job_name: Lint