# $schema: https://json.schemastore.org/github-workflow.json

name: Deploying

on:
  workflow_call:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SERVER_IP }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml, Makefile"
          target: "/srv/${{ vars.PROJECT_NAME }}"

      - name: Start Docker services
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SERVER_IP }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/${{ vars.PROJECT_NAME }}
            docker compose up -d
            make migrate

      - name: Notify Telegram on Failure
        if: failure()
        uses: ./.github/actions/telegram-notify
        with:
          job_name: Deploy
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: Cleanup Docker images on runner
        if: always()
        run: docker image prune -a -f || true