# $schema: https://json.schemastore.org/github-workflow.json

name: Linting

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --dev

      - name: Check using Ruff
        run: uv run ruff check .

      - name: Check using Ruff formatter
        run: uv run ruff format --check .

      - name: Check Type Hints
        run: uv run mypy .

      - name: Send Telegram Notification
        if: failure()
        uses: ./.github/actions/telegram-notify
        with:
          job_name: Linting
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
