# $schema: https://json.schemastore.org/github-workflow.json

name: Linting

on:
  workflow_call:

jobs:
  lint:
    name: Lint and Type Check
    runs-on: self-hosted
    timeout-minutes: 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Restore mypy cache
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-${{ runner.python.version }}-mypy-${{ hashFiles('**/uv.lock', '**/pyproject.toml') }}

      - name: Install dependencies
        run: uv sync --frozen --dev

      - name: Check using Ruff
        run: uv run ruff check .

      - name: Check using Ruff formatter
        run: uv run ruff format --check .

      - name: Check Type Hints
        run: uv run mypy .

      - name: Save mypy cache
        uses: actions/cache@v4
        if: success()
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-${{ runner.python.version }}-mypy-${{ hashFiles('**/uv.lock', '**/pyproject.toml') }}

      - name: Send Telegram Notification
        if: failure()
        uses: ./.github/actions/telegram-notify
        with:
          job_name: Linting
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
