# $schema: https://json.schemastore.org/github-workflow.json

name: Testing

on:
    workflow_call:

jobs:
    test:
        name: Test project
        runs-on: self-hosted
        timeout-minutes: 3
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run tests
              run: make tests

            - name: Send Telegram Notification
              if: failure()
              uses: ./.github/actions/telegram-notify
              with:
                  job_name: Testing
                  title: ❌ Test Failure ❌
                  to: ${{ secrets.TELEGRAM_CHAT_ID }}
                  token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
