# $schema: https://json.schemastore.org/github-workflow.json

name: Testing

on:
    workflow_call:

env:
  COMPOSE_BAKE: true

jobs:
  test:
    name: Test project
    runs-on: self-hosted
    timeout-minutes: 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env from .env.example
        run: |
          cp .env.example .env
          export ENV_MODE=development

      - name: Run Project
        run: make up

      - name: Run tests
        run: make test

      - name: Stop Project
        run: make down

      - name: Send Telegram Notification
        if: failure()
        uses: ./.github/actions/telegram-notify
        with:
          job_name: Testing
          title: ❌ Test Failure ❌
          to: ${{ secrets.TELEGRAM_NOTIFIER_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_NOTIFIER_BOT_TOKEN }}